{% set name = "slycot" %}
{% set version = "0.3.3" %}
{% set sha256 = "e22f5d9b611328b1ea9cac32ea077043c327765f215ebb49ff41746d8e217e1d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #url: file:///home/repa/control/{{ name }}-{{ version }}.tar.gz
  # temporary, for testing. 
  url: https://github.com/repagh/Slycot/archive/update-buildconfig.tar.gz
  # url: https://github.com/python-control/Slycot/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1004

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - flang                      # [win]
    - {{ compiler('c') }}        # [not osx]
    - gcc                        # [osx]

  host:
    - mkl                        
    - python
    - numpy
    - scikit-build

  run:
    - python
    - mkl
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - slycot

about:
  home: https://github.com/python-control/Slycot
  dev_url: https://github.com/python-control/Slycot
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: 'Slycot: a wrapper for the SLICOT control and systems library'
  description: |
    Slycot wraps the SLICOT library which is used for control and systems
    analysis.

extra:
  recipe-maintainers:
    - moorepants
    - murrayrm
    - repagh
