travis:
  secure:
    BINSTAR_TOKEN: Lt4+SwOjmablZH/b/78rYr7E9YbY05wGLbNGuVxi8PbFOfHgR0vJBPL65d4LZdV0sUYCXIdC1u6b5kVsrNxH4Z6eX9pC/u4QUAXtO2jb5muGyFv7QFIU1f2OBQvFqUnMux5lTTEUg4SDCvrQ9udnfpyzXswWA92Z5JCBYxfyAWBKKHnA0MVI1K3Fg2rDDELQyrLWQQLdpXDgk/eGh8q/QZ7Wo97gu4RkEB4OprmHnGccroikNCUYivNkpdZz48AzUsNNSLzAp3jPPEJuFcU3vnJv01/hvYaUHA7FupVkH+H79yeBS/kc0uV/YHKCUXep/xkopj+7kLgcTdfGpyRixoUFhaNJxjXq3TZ0kQczEFI2qxzy9/oEzH93rgMqtXzTnHPUpmOi3VO7A1+XFuPyQCG1ms+wBDvzh46hqu3b4uQL4lCHbjfTuOA663jK/LAvzJsZy7O54awjmuQ1mQiJDIk21f4hAP7v1ZCsWlRlczdKzCDbWMEo0IvMslXJKSiYSd6jxSSP98phnysPJYmtNIXpnsJ+Lys/GvPPy52NCSiQuCItfxAyRZr4y5j+Y3Os6nFdO9kbxf0sVxVq/0ZATJquQYJuhYYCTijZFAB1ulZUCLwj+096m54p3I2SX08wUcAXJXexSewcdAzr6SkaNu/R9yHC0twjG3WMZLnVSd0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
