travis:
  secure:
    BINSTAR_TOKEN: YagVxrSo+mwipX087+4nB+QV1imWiuf43Fkiy4W6Yrv4kYABzpQ3ATLm1Ut5Lx0BPZbi2ocOnZUqXUBhz7ODISyY2XJ67BY7uVOBI63UyXfo8AGQFX+Qy97jLuq3lDMcU9FfxiMCeDMqhP1I2XvFU447frdzFY3l+aTwSjH/2ZXXFRT5nhBegF+vCEBWJahXqSOefet+JPcEC+pST586H1Ey5Z59Q7fMExz0Whj310wBIpOhbY00ICoI39Z2qpHZtvC2+MUacKVNwzB+IH2V4SgREAQyyW1Yzs8O3cL1EPuWU3OCmEy7qr4n4dcO7FGBbid2Fwb1MfTCWVk9riSZcypaWjPaA4tN9VZrjL+IYoXBAGysFdNXDiOcg4zyE0vWxZCz+59e1P3/Jjo1STBQSUYrrBUe8y+30YT+sEWbsSvpNld+czSLKB+n+jN0rZyoQ9//8IBhGHz2lK9KoO3j2Ev8NIxlp1SNGc6GTWrfIsDg8I/26pKchXZOxjcUVArqE5uXrR6lkNAjswd9ubNhQylYNGjW00D5pt2Y71TmmGRUK/iEj07qOXHjzH2AC8oa+f/ue/D6ZOTjeCfD0fbsUGk8K1XZP3PfhoEIqHjt0JbDoZ1DNCZLWzCRcBM1LO14J89wtUJfYFoq8eeGdgXGyl5OfbvWh1+BcjBEtAbxiZ0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
